# PowerShell script for Windows integrated authentication to SAP
# This script authenticates to SAP OData services and saves cookies

param(
    [Parameter(Mandatory=$true)]
    [string]$ServiceUrl,
    
    [string]$OutputFile = "$env:USERPROFILE\.odata-mcp\cookies.txt",
    
    [switch]$SaveToCredentialManager
)

Write-Host "SAP OData Authentication Helper" -ForegroundColor Cyan
Write-Host "===============================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Service URL: $ServiceUrl"
Write-Host "Output File: $OutputFile"
Write-Host ""

# Create web session with Windows credentials
$session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
$cookies = @{}

try {
    Write-Host "Authenticating with Windows credentials..." -ForegroundColor Yellow
    
    # Make request with integrated authentication
    $response = Invoke-WebRequest -Uri $ServiceUrl `
        -UseDefaultCredentials `
        -SessionVariable session `
        -MaximumRedirection 20 `
        -ErrorAction Stop
    
    Write-Host "✓ Authentication successful!" -ForegroundColor Green
    
} catch {
    # Check if we got cookies even with an error
    if ($session.Cookies.Count -gt 0) {
        Write-Host "⚠ Service returned error but cookies were captured" -ForegroundColor Yellow
    } else {
        Write-Host "✗ Authentication failed: $_" -ForegroundColor Red
        exit 1
    }
}

# Extract all cookies
$uri = [System.Uri]$ServiceUrl
$allCookies = $session.Cookies.GetCookies($uri.Scheme + "://" + $uri.Host)

Write-Host ""
Write-Host "Captured cookies:" -ForegroundColor Cyan
foreach ($cookie in $allCookies) {
    $cookies[$cookie.Name] = $cookie.Value
    Write-Host "  - $($cookie.Name): $($cookie.Value.Substring(0, [Math]::Min(20, $cookie.Value.Length)))..." -ForegroundColor Gray
}

# Check for important SAP cookies
$important = @("MYSAPSSO2", "SAP_SESSIONID")
$found = $false
foreach ($name in $important) {
    foreach ($key in $cookies.Keys) {
        if ($key -like "*$name*") {
            Write-Host "  ✓ Found $name cookie" -ForegroundColor Green
            $found = $true
        }
    }
}

if (-not $found) {
    Write-Host "  ⚠ Warning: No SAP authentication cookies found" -ForegroundColor Yellow
}

# Create output directory
$outputDir = Split-Path $OutputFile -Parent
if (!(Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

# Save cookies in Netscape format
$domain = $uri.Host
$cookieContent = @(
    "# Netscape HTTP Cookie File",
    "# This file was generated by SAP Auth PowerShell script",
    ""
)

foreach ($cookie in $allCookies) {
    # Format: domain, flag, path, secure, expiration, name, value
    $expiry = if ($cookie.Expires -eq [DateTime]::MinValue) { "0" } else { [int]($cookie.Expires - [DateTime]::UnixEpoch).TotalSeconds }
    $secure = if ($cookie.Secure) { "TRUE" } else { "FALSE" }
    $line = "$domain`tTRUE`t$($cookie.Path)`t$secure`t$expiry`t$($cookie.Name)`t$($cookie.Value)"
    $cookieContent += $line
}

# Write to file
$cookieContent | Out-File -FilePath $OutputFile -Encoding UTF8 -Force

Write-Host ""
Write-Host "✓ Cookies saved to: $OutputFile" -ForegroundColor Green

# Optionally save to Windows Credential Manager
if ($SaveToCredentialManager) {
    Write-Host ""
    Write-Host "Saving to Windows Credential Manager..." -ForegroundColor Yellow
    
    # Convert cookies to JSON for storage
    $credData = @{
        ServiceUrl = $ServiceUrl
        Cookies = $cookies
        Timestamp = (Get-Date).ToString("o")
    } | ConvertTo-Json -Compress
    
    # Use cmdkey to store (alternative: use .NET CredentialManager)
    $credName = "odata-mcp:" + $uri.Host
    
    # Note: This is a simplified example. Real implementation would use
    # Windows Credential Manager API for secure storage
    
    Write-Host "✓ Saved to credential: $credName" -ForegroundColor Green
}

# Show usage instructions
Write-Host ""
Write-Host "To use these cookies with odata-mcp:" -ForegroundColor Cyan
Write-Host "  odata-mcp --cookies `"$OutputFile`" --service `"$ServiceUrl`"" -ForegroundColor White
Write-Host ""
Write-Host "For MCP configuration, add to your config:" -ForegroundColor Cyan
Write-Host @"
  {
    "command": "odata-mcp.exe",
    "args": ["--cookies", "$($OutputFile -replace '\\', '\\')", "--service", "$ServiceUrl"]
  }
"@ -ForegroundColor White